### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by dw3phCnR** [omegastripes/VBA-JSON-parser#1]
Please, can you write some examples of how to use it?

Any documentation will be really appreciated.

**Comment by omegastripes** [comment]
@dw3phCnR  good point! I will create some manual. Currently there is few examples could be found on SO https://stackoverflow.com/search?q=user%3A2165759+is%3Aanswer+json.bas

**Comment by dw3phCnR** [comment]
I'm getting error in:
JSON.Parse sJSONString, vJSON, sState

vJSON is coming Null from this JSON. I checked Sub Parse and it appears that it does not recognize the structure. When I write Tab characters it works.
Does not works
![image](https://user-images.githubusercontent.com/35775976/35539689-a76a83c4-0520-11e8-9ed0-54a0c7f03a21.png)

Works
![image](https://user-images.githubusercontent.com/35775976/35539930-8ae8d948-0521-11e8-92c0-abe76117afb3.png)

Please, be notified that is the same data!

**Comment by Deetiantai** [comment]
just read your code, but same question as above. how to use it , or  under what condition  we can using it.
would you pls give more detail for using.
thanks a lot !
