### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by yfrindel** [omegastripes/VBA-JSON-parser#10]
Hi,

Please, could you tell me how I can access to the last element of my JSON string please ?

![image](https://user-images.githubusercontent.com/22955005/72887839-bbed1480-3d0c-11ea-938d-7b13d47b3170.png)

I tried with the following code, but the vJSON seems not correct : 

![image](https://user-images.githubusercontent.com/22955005/72887966-f8207500-3d0c-11ea-816c-2e5cec5b8593.png)

Thx

**Comment by omegastripes** [comment]
```vba
historyItem = vJSON("measures")(0)
valueStr = historyItem(UBound(historyItem))("value")
```

**Comment by yfrindel** [comment]
Thank you for the answer, but I have still a problem : 
![image](https://user-images.githubusercontent.com/22955005/72889811-d5905b00-3d10-11ea-8d38-1319f818b761.png)

that's the value of the sJSONstring : 
`"{"paging":{"pageIndex":1,"pageSize":100,"total":3},"measures":[{"metric":"coverage","history":[{"date":"2019-05-29T16:35:40+0100","value":"0.0"},{"date":"2019-05-30T07:48:40+0100","value":"0.0"},{"date":"2019-06-18T10:44:37+0100","value":"0.0"}]}]}"`

**Comment by omegastripes** [comment]
```vba
historyItem = vJSON("measures")(0)("history")
valueStr = historyItem(UBound(historyItem))("value")
```

**Comment by yfrindel** [comment]
Excellent, it works. Thanks
