### ISSUE TITLE
Won't run after import

### ISSUE THREAD

**Issue by sfegsetsfe** [omegastripes/VBA-JSON-parser#12]
After import to excel, the code won't run and it seems there's an extra `End Sub` in the code. Also, after I delete the extra `End Sub`. Run `JSON.Serialize(someDictionary)` will result in error.

**Comment by omegastripes** [comment]
Oh my bad! I will remove extra `End Sub`.
BTW, if I delete that `End Sub`, then `JSON.Serialize(someDictionary)` works OK for me. Could you please show the code and specify the error you have?
