### ISSUE TITLE
Change all Dictionary references to specify Scripting.Dictionary

### ISSUE THREAD

**Issue by hollysmoke** [omegastripes/VBA-JSON-parser#13]
Avoids conflicts with Office

**Comment by omegastripes** [comment]
@hollysmoke Thanks for the input. What is the exact conflict? Could you please share some more info? I want to note, that currently the type is specified as `Dictionary` but not `Scripting.Dictionary` to make the code compatible with [VBA-Dictionary](https://github.com/VBA-tools/VBA-Dictionary) on Mac, and use it by simply inserting the reference, with no code change.

**Comment by hollysmoke** [comment]
@omegastripes If I leave it at Dictionary the JSON.bas library will not compile see screenshot:
![image](https://user-images.githubusercontent.com/61952511/76244144-baad7380-61f6-11ea-9640-2ab34d3dc210.png)
I get the error "Invalid use of New keyword"
Here is a screenshot of the current References:
![image](https://user-images.githubusercontent.com/61952511/76244312-0b24d100-61f7-11ea-902f-96debb7865e9.png)
I suspect the Word 15.0 object library

Hope this helps

**Comment by hollysmoke** [comment]
@omegastripes I have confirmed that Word 15.0 has a Dictionary object:
![image](https://user-images.githubusercontent.com/61952511/76244732-df561b00-61f7-11ea-813d-556a3ef492d9.png)

**Comment by hollysmoke** [comment]
@omegastripes However if I move the Scripting Runtime ahead of Word then VJSON compiles without error:
![image](https://user-images.githubusercontent.com/61952511/76245065-77540480-61f8-11ea-8905-d87f46cbdbb9.png)
