### ISSUE TITLE
Parser is failing to handle a JSON containing git issues

### ISSUE THREAD

**Issue by michelreyrolle** [omegastripes/VBA-JSON-parser#14]
Hello,

I want to convert a set of git issues (exported using a simple cURL command) from the output JSON file into a flattened Excel worksheet. Attached is the structure of JSON file:
[sample-issues.zip](https://github.com/omegastripes/VBA-JSON-parser/files/4567340/sample-issues.zip)

Using the sample test code, I get the following error "Invalid JSON response". The JSON file seems to have been parsed correctly  (see watch window below) however the type of sState is **Array** while **Object** is expected in the provided example. Do you have a sample VBA code to flatten any JSON structure to a worksheet (something similar to this online converter https://www.convertcsv.com/json-to-csv.htm)?

![image](https://user-images.githubusercontent.com/25659991/80860742-301f4880-8c6a-11ea-8712-f55a7d0ca82c.png)

**Comment by omegastripes** [comment]
@michelreyrolle the sample code is designed to process JSON from trirand, which is differ from the one you shared.

Replace `Case sState <> "Object"` with `Case sState <> "Array"`, remove the condition check `vJSON.Exists("rows")`, and replace `Output ThisWorkbook.Sheets(1), vJSON("rows")` with `Output ThisWorkbook.Sheets(1), vJSON`.

I guess you need the table output only, but not flatten, so remove all lines starting from `JSON.Flatten`.

**Comment by michelreyrolle** [comment]
@omegastripes In the meantime I found an example that flattens my structure into Excel in the list of examples you reference: https://stackoverflow.com/questions/51097249/how-to-display-my-json-object-in-good-format-in-vba-excel/51147537#51147537

Great stuff! Thanks a lot for this very valuable code.
