### ISSUE TITLE
parser become very slow

### ISSUE THREAD

**Issue by sfegsetsfe** [omegastripes/VBA-JSON-parser#17]
Hi, suddenly, it becomes very slow to parse JSONString to Dictionary. I've tested with multiple computers. Did you notice this issue?

**Comment by omegastripes** [comment]
It's quite fast if the dataset isn't too large.

**Comment by omegastripes** [comment]
The issue description is too broad, neither dataset size nor parsing elapsed time are specified.

**Comment by omegastripes** [comment]
@sfegsetsfe Last update may help to improve performance, check [here](https://github.com/omegastripes/VBA-JSON-parser#douglas-crockford-json2js-implementation-for-vba)
