### ISSUE TITLE
Error detecting structure in JSON.Parse

### ISSUE THREAD

**Issue by dw3phCnR** [omegastripes/VBA-JSON-parser#3]
I'm getting error in:
JSON.Parse sJSONString, vJSON, sState

vJSON is coming Null from this JSON. I checked Sub Parse and it appears that it does not recognize the structure. When I write Tab characters it works.
Does not works
![image](https://user-images.githubusercontent.com/35775976/35539689-a76a83c4-0520-11e8-9ed0-54a0c7f03a21.png)

Works
![image](https://user-images.githubusercontent.com/35775976/35539930-8ae8d948-0521-11e8-92c0-abe76117afb3.png)

Please, be notified that is the same data!

**Comment by omegastripes** [comment]
@dw3phCnR That is due to wrong pattern modification [in the last commit](https://github.com/omegastripes/VBA-JSON-parser/commit/9715364d0fcc78d9cfb7bb707028f3b034c4adb1):
> 1. Fixed regex pattern for unnecessary spaces removing:
	"\s{2,}"

The pattern should be changed back to `"\s+"` to solve the problem. I will do a new commit to fix the issue.

**Comment by dw3phCnR** [comment]
Thank you.
