### ISSUE TITLE
关于Win7系统本身一些机制, 导致0.01变成.01, 使JSONString无效

### ISSUE THREAD

**Issue by doom189** [omegastripes/VBA-JSON-parser#4]
![image](https://user-images.githubusercontent.com/31546872/56345139-9d904080-61f1-11e9-95c9-bdd0fb5bf040.png)
![image](https://user-images.githubusercontent.com/31546872/56345216-c57fa400-61f1-11e9-8127-8e2841b06740.png)

请问应该如何解决该问题(Win10没有该问题)

**Comment by omegastripes** [comment]
Could you please provide a minimal VBA code that can be used to reproduce the problem?

**Comment by doom189** [comment]
需要使用Win7测试才能重现问题
[最小代码.zip](https://github.com/omegastripes/VBA-JSON-parser/files/3097525/default.zip)

**Comment by omegastripes** [comment]
Seems there are some known encoding issues with the code, could you please rewrite it using ASCII charset only?

![encoding error](https://user-images.githubusercontent.com/3822668/56694310-15c59d00-66ef-11e9-9036-4b4a6209d452.png)

**Comment by doom189** [comment]
非常抱歉, 那么晚才来更新问题, 请您谅解.
回复: 似乎代码中存在一些已知的编码问题，您能否仅使用ASCII字符集重写它？
答: 因为我用的是中文简体的Windows, 使用的Office2010中文简体, 可能导致.xlsm文件在非中文系统上出现乱码.(乱码的都是中文)

回归到该问题本身, 我通过Regex正则处理后已经可以在Windows7上正常使用了(但是不是存为数值了, 而是存为文本)
        ' RegExStr函数(被处理文本, 正则表达式, True替换_默认为False, 被替换值_True时必填)
        YL = RegExStr(Range("K10").Value, "\d+(?:\.\d+)?|\.\d+") ' 用量, 获得数值部分 (文本类型)
        YL = RegExStr(YL, "^\.", True, "0.") ' 用量, 替换开头是.001的为"0.001" (文本类型)
        JSONOBJ("KangChenDianFen")("YongLiang") = YL ' 抗沉淀粉的用量=用量
[最小代码.txt](https://github.com/omegastripes/VBA-JSON-parser/files/3160604/default.txt)

**Comment by doom189** [comment]
[SimpleCodeASCII.zip](https://github.com/omegastripes/VBA-JSON-parser/files/3161100/SimpleCodeASCII.zip)
已去除中文注释, 应该不会有问题了

**Comment by omegastripes** [comment]
@doom189 Sorry, still have no idea how to reproduce the issue you described. The numbers serialized with `JSON.Serialize` method is valid for me (Win7 HB x64, MS Office 2010 x64).
![VBE](https://user-images.githubusercontent.com/3822668/57451397-c5f7e180-7269-11e9-8b2f-e8291cdfd477.png)

**Comment by omegastripes** [comment]
@doom189 Anyway, you may try to fix the issue with fix missing integer part zero: add the line `If Left(.Item(.Count - 1), 1) = "." Then .Item(.Count - 1) = "0" & .Item(.Count - 1)` right after the line `.Item(.Count) = Replace(vElement, ",", ".")` in `JSON` module:
![fix missing integer part zero](https://user-images.githubusercontent.com/3822668/57452129-c8f3d180-726b-11e9-827a-3292e735240d.png)

**Comment by doom189** [comment]
@omegastripes 好的大佬, 已经解决了, 您真的是Six Six Six 
PS: 该问题是因为Windows7简体中文版的系统本身的日期时间还有数据格式设定问题导致的, 需要进系统修改数据格式才能正常使用(如图), 如果加入该代码, 就可以不进去系统设定, 也可以不修改正则把字符替换成文本了
![image](https://user-images.githubusercontent.com/31546872/57501112-ce5b2580-7318-11e9-8021-103abf698d87.png)

**Comment by omegastripes** [comment]
@doom189 Could you please confirm that the problem is solved, and I can close the issue?

**Comment by doom189** [comment]
@omegastripes 已解决, 谢谢您!
