### ISSUE TITLE
Does this work for anybody?

### ISSUE THREAD

**Issue by jromano1** [omegastripes/VBA-JSON-parser#7]
This code looks great, but I can't get it to work at all.  I've downloaded and imported the bas file part and copied the example into a standard module.  When I run the "TEST" module, I immediately get "Compile Error:  Expected: line number or label or statement or end of statement" on the first character of <!DOCTYPE html>

Am I missing something obvious?

Thanks for any help

**Comment by omegastripes** [comment]
Hi @jromano1 Have you followed the steps described under the cut in the Deployment section of Readme?

**Comment by jromano1** [comment]
Yes, at least I tried to.  First character of the json bas file that I downloaded and imported to the vba editor.

**Comment by omegastripes** [comment]
@jromano1 not sure which is one, could you please post the screenshot of VBA editor window with highlighted characters..

**Comment by jromano1** [comment]
@omegastripes - thanks for your time... 
I don't have the ability to screenshot, but when I try to run the test, I get the error from the first line in the bas service code.  I didn't modify it at all, just imported per the instructions.  But I absolutely hate GITHUB so it's quite possible I missed or misunderstood something!

```
<!DOCTYPE html>
<html lang="en">
  <head>

```

**Comment by omegastripes** [comment]
@jromano1 OK let's check it up, take a look at this [video](https://yadi.sk/i/_a9S2lfkIfPIbw)

**Comment by jromano1** [comment]
@omegastripes - Thank you - unfortunately my workplace firewall is preventing me from opening the video link from here.  I will check it out later tonight from home.

**Comment by omegastripes** [comment]
@jromano1 Actually nothing new in that video, I just completed all the steps from Deployment section, copy-paste and launched the sample code, and showed results. I'm on Win7 HB x64, MS Office 2010 x64.

**Comment by jromano1** [comment]
@omegastripes Okay, that was really my only question - if somebody else can figure out how to make it work then I'm happy to spend some time working on it as well!  If nobody else was able to make it happen, then I wasn't going to waste time trying.  Appreciate the feedback.
