### ISSUE TITLE
vJSON.Item is failing

### ISSUE THREAD

**Issue by manavilai** [omegastripes/VBA-JSON-parser#8]
i have a simple json file..
{"employee" : {"name" :"vivek"}}
i am trying to retrieve the employee from this json.
i do the below command
JSON.Parse sJSONString, vJSON, sState
and later do 
sCont = vJSON("employee")

i get the below error. please help

![image](https://user-images.githubusercontent.com/8392059/60345308-5c2cc600-99d6-11e9-9aa4-44649977dab1.png)

**Comment by omegastripes** [comment]
Hi @manavilai Try
`sCont = vJSON("employee")("name")`
or
`Set sCont = vJSON("employee")`

**Comment by omegastripes** [comment]
Hi @manavilai Have you tried the code? Does it work for you?

**Comment by manavilai** [comment]
hi @omegastripes , 

thank you so much it works for me

regards,
manavilai
